/* Rhinoforum 2026 — programme réel (source: site officiel).
   Tuple format: [id, start, end, roomKey, themeKey, formatKey, title, speakers]
   speakers: "" or "Nom; Nom" — first entry treated as moderator for sessions with a programme. */
(function () {
  const THEMES = {
    AP: { label: 'Allergologie / Pneumologie', short: 'Allergo', hue: 232 },
    RP: { label: 'Rhinosinusites / Polypose', short: 'Polypose', hue: 318 },
    SR: { label: 'Septorhinoplasties', short: 'Septo-rhino', hue: 282 },
    TC: { label: 'Techniques chirurgicales', short: 'Chirurgie', hue: 12 },
    TU: { label: 'Tumeurs et cancers', short: 'Tumeurs', hue: 64 },
    UR: { label: 'Urgences', short: 'Urgences', hue: 28 },
    IM: { label: 'Imagerie naso-sinusienne', short: 'Imagerie', hue: 196 },
    OD: { label: 'Odorat', short: 'Odorat', hue: 152 },
    SO: { label: 'Sommeil', short: 'Sommeil', hue: 258 },
    DV: { label: 'Divers', short: 'Divers', hue: 110 },
    SE: { label: 'Séance extraordinaire', short: 'Extraordinaire', hue: 344 },
    PS: { label: 'Programme Social', short: 'Social', hue: 38 },
  };

  const FORMATS = {
    AT: 'Atelier',
    CC: "Cas Cliniques / Avis d'Experts",
    CO: 'Controverse',
    DI: 'Divers',
    IN: 'Innovation',
    LE: 'Lecture',
    RE: 'Recommandations',
    SY: 'Symposium',
    VC: 'Séance Vidéo Chirurgicale',
    TR: 'Table Ronde',
  };

  const ROOMS = {
    AmphiA: { name: 'Amphi A', cru: 'Saint-Estèphe' },
    AmphiC: { name: 'Amphi C', cru: 'Monbazillac' },
    Margaux: { name: 'Margaux', cru: 'Salle G1+G2' },
    Pessac: { name: 'Pessac-Léognan', cru: 'Salle F1+F2' },
    Pomerol: { name: 'Pomerol', cru: 'Salle D1+D2' },
    StJulien: { name: 'Saint Julien', cru: 'Salle H1+H2' },
    Sauternes: { name: 'Sauternes', cru: 'Salle E1+E2' },
    Hall: { name: 'Hall Expo', cru: 'Exposition' },
  };
  // column order for the grid view
  const ROOM_ORDER = ['AmphiA', 'AmphiC', 'Margaux', 'Pessac', 'Pomerol', 'StJulien', 'Sauternes', 'Hall'];

  const JEU = [
    ['S7', '12:30', '13:15', 'Hall', 'PS', 'DI', "Cocktail d'Accueil", ''],
    ['S2', '13:15', '13:45', 'AmphiA', 'TC', 'VC', 'Comment faire une voie prélacrymale ?', 'Ahmed ALHARBI'],
    ['S21', '13:15', '13:45', 'Margaux', 'DV', 'AT', 'Place de la rhinomanométrie en pré-opératoire de l’obstruction nasale', 'Maxime FIEUX'],
    ['S17', '13:15', '13:45', 'Pessac', 'TC', 'AT', 'Chirurgie endoscopique des sinus : les repères anatomiques à reconnaître', 'Vincent BEDARIDA'],
    ['S11', '13:15', '13:45', 'Pomerol', 'TU', 'AT', "Les bons réflexes devant la découverte d'une tumeur naso-sinusienne", 'Nicolas SAROUL'],
    ['S25', '13:15', '13:45', 'StJulien', 'DV', 'AT', 'Pathologies du sinus frontal : quelles solutions ?', 'Guillaume DE BONNECAZE'],
    ['S15', '13:15', '14:20', 'Sauternes', 'AP', 'CC', 'RETEX ORL-PNEUMO sur les biothérapies', 'Ludovic DE GABORY; Laurent GUILLEMINAULT; Pierre-Olivier GIRODET; Jean-Baptiste LECANU; Geoffrey MORTUAIRE'],
    ['S3', '13:50', '14:20', 'AmphiA', 'TC', 'VC', 'Rhinopoièse latérale : lambeaux géniens, frontal et de Schmid-Meyer', 'Gilles POISSONNET'],
    ['S22', '13:50', '14:20', 'Margaux', 'DV', 'AT', 'Céphalées et sinusites : stratégie diagnostique', 'Maxime HUMBERT'],
    ['S69', '13:50', '14:20', 'Pessac', 'AP', 'AT', 'Les Prick-tests en pratique dans la rhinite allergique', 'Clémentine DAVEAU'],
    ['S12', '13:50', '14:20', 'Pomerol', 'UR', 'RE', 'Épistaxis sous anticoagulant / antiagrégant : recommandations AFR', 'Florian CHATELET'],
    ['S26', '13:50', '14:20', 'StJulien', 'AP', 'AT', 'Intégrer une activité allergologique en consultation ORL libérale', 'Pascal FLORES'],
    ['S4', '14:25', '15:30', 'AmphiA', 'AP', 'LE', "Soigner l'épithélium pour une réussite optimale après chirurgie endoscopique", 'Martin DESROSIERS'],
    ['S122', '14:25', '15:30', 'Sauternes', 'AP', 'SY', "Symposium ALK — Rhinite allergique : de l'errance à la décision", 'Clémentine DAVEAU; Guillaume DE BONNECAZE; Laurent GUILLEMINAULT'],
    ['S134', '15:30', '16:15', 'Hall', 'PS', 'DI', "Pause et visite de l'exposition", ''],
    ['S9', '15:30', '17:00', 'Hall', 'SE', 'DI', 'Ateliers de dissection pour les internes', 'Mélodie KERIMIAN; Chloé MONNOT'],
    ['S5', '16:15', '17:20', 'AmphiA', 'SE', 'IN', "Les teasing de l'innovation INOV'R", 'Ludovic DE GABORY; Valentin FAVIER; Patrice GALLET'],
    ['S23', '16:15', '16:45', 'Margaux', 'UR', 'AT', 'Gestion des épistaxis dans la maladie de Rendu-Osler', 'Florent CARSUZAA'],
    ['S19', '16:15', '16:45', 'Pessac', 'DV', 'AT', 'Rhinoliquorrhée spontanée : du diagnostic à la prise en charge', 'Cécile RUMEAU'],
    ['S13', '16:15', '16:45', 'Pomerol', 'TC', 'AT', 'Trucs et astuces pour améliorer ses compétences en chirurgie endonasale', 'Azeddine LACHKAR'],
    ['S27', '16:15', '17:20', 'StJulien', 'TC', 'TR', 'Optimiser la qualité des réparations des PDS de la pyramide nasale', 'Gilles POISSONNET; Philippe BOUDARD; Olivier MALARD'],
    ['S16', '16:15', '17:15', 'Sauternes', 'RP', 'SY', 'Symposium GSK — Polypose naso-sinusienne : quels changements pour 2026 ?', 'Elie SERRANO; Geoffrey MORTUAIRE; Jean-François PAPON'],
    ['S24', '16:50', '17:20', 'Margaux', 'RP', 'AT', 'Les maladies de système en rhinologie : quand y penser ?', 'Emmanuelle MOUCHON; Grégory PUGNET'],
    ['S20', '16:50', '17:20', 'Pessac', 'TC', 'VC', 'La chirurgie sur patient éveillé : simple, efficace et rentable', 'Justin MICHEL; Thomas RADULESCO'],
    ['S14', '16:50', '17:20', 'Pomerol', 'RP', 'AT', 'La prise en charge des sinusites fongiques allergiques', 'Ahmed ALHARBI'],
    ['S6', '17:30', '18:40', 'AmphiA', 'SE', 'DI', "Cérémonie d'ouverture", 'Ludovic DE GABORY; Gilles DE REVEL'],
    ['S10', '18:40', '19:30', 'Hall', 'PS', 'DI', 'Cocktail de bienvenue', ''],
  ];

  const VEN = [
    ['S30', '09:00', '09:55', 'AmphiA', 'AP', 'RE', "Recommandations de l'AFR par l'exemple : rhinites allergiques", 'Justin MICHEL; Dario EBODE'],
    ['S114', '09:00', '09:30', 'AmphiC', 'RP', 'LE', 'Implication clinique de la mucine éosinophilique', 'Stephan VLAMINCK'],
    ['S29', '09:00', '09:30', 'Margaux', 'SR', 'CO', 'Quelle contention après septoplastie ?', 'Jean-Baptiste LECANU'],
    ['S32', '09:00', '10:00', 'Pessac', 'RP', 'SY', 'Symposium GSK — Biothérapies émergentes dans la polypose nasale', 'Cécile RUMEAU; Maxime FIEUX; Valentin FAVIER'],
    ['S28', '09:00', '09:30', 'Pomerol', 'TC', 'AT', 'DCR endoscopique : indications et situations complexes', 'Mélodie KERIMIAN'],
    ['S47', '09:00', '09:30', 'StJulien', 'SO', 'AT', 'Nez, ronflement et apnée : que penser ?', 'Philippe ROMBAUX'],
    ['S31', '09:00', '09:55', 'Sauternes', 'DV', 'CC', "Cas cliniques avis d'experts sous l'égide de la SOFA", 'Thomas RADULESCO; Ludovic DE GABORY; Amandine LECHOT'],
    ['S169', '09:30', '10:00', 'AmphiC', 'TU', 'AT', 'La radiothérapie des sinus : les essentiels à savoir', 'Charles DUPIN'],
    ['S34', '09:30', '10:00', 'Margaux', 'DV', 'LE', "Les sinusites pédiatriques : état de l'art", 'François SIMON'],
    ['S33', '09:30', '10:00', 'Pomerol', 'TC', 'AT', 'Techniques de chirurgie turbinale : existe-t-il un gold standard ?', 'Jean-François PAPON'],
    ['S40', '09:30', '10:35', 'StJulien', 'TC', 'TR', 'Reconstruire les PDS transfixiantes nasales : les meilleurs choix', 'Olivier MALARD; Martin PENICAUD; Khaled AL TABAA'],
    ['S35', '10:05', '10:35', 'AmphiA', 'TC', 'VC', 'La chirurgie du papillome inversé, particularités', 'Nicolas SAROUL; Clémentine DAVEAU'],
    ['S115', '10:05', '10:35', 'AmphiC', 'DV', 'AT', "Où en est-on pour le syndrome du nez vide ?", 'Guillaume BUIRET'],
    ['S39', '10:05', '10:35', 'Margaux', 'AP', 'AT', 'La rhinite non allergique : où en sommes-nous en 2026 ?', 'Semia SAHTOUT'],
    ['S38', '10:05', '10:35', 'Pessac', 'DV', 'RE', "Recommandations de l'AFR par l'exemple : les vasoconstricteurs", 'Geoffrey MORTUAIRE'],
    ['S36', '10:05', '10:35', 'Pomerol', 'RP', 'AT', 'Éducation thérapeutique autour de la polypose', 'Emilie BEQUIGNON'],
    ['S37', '10:05', '10:35', 'Sauternes', 'DV', 'AT', 'Tout savoir sur le lavage nasal en toutes circonstances', 'Ludovic DE GABORY'],
    ['S41', '10:35', '11:05', 'Hall', 'PS', 'DI', "Pause et visite de l'exposition", ''],
    ['S42', '11:05', '12:00', 'AmphiA', 'SR', 'LE', 'La septoplastie et la SRP par désarticulation expliquée à mes élèves', 'Roger JANKOWSKI'],
    ['S48', '11:05', '11:30', 'AmphiC', 'SR', 'AT', 'La septoplastie pour les débutants', 'Amandine LECHOT'],
    ['S129', '11:05', '11:30', 'Margaux', 'DV', 'AT', 'La phytothérapie et la rhinologie', 'Marc DURAND'],
    ['S46', '11:05', '11:30', 'Pessac', 'AP', 'LE', "L'IA appliquée au diagnostic de la rhinite allergique", 'Julien GORET'],
    ['S43', '11:05', '11:30', 'Pomerol', 'UR', 'AT', 'Sinusite fongique invasive : la reconnaître et la traiter', 'Florian CHATELET'],
    ['S50', '11:05', '11:30', 'StJulien', 'TC', 'VC', 'Abord endoscopique du sinus frontal', 'Florent CARSUZAA'],
    ['S45', '11:05', '12:00', 'Sauternes', 'RP', 'SY', 'Symposium Sanofi Regeneron — Polypose naso-sinusienne : une vision à 360°', 'Ludovic DE GABORY; Valentin FAVIER; Maxime FIEUX'],
    ['S116', '11:35', '12:00', 'AmphiC', 'DV', 'LE', "Que peut-on demander à l'IA pour la prise en charge de nos patients ?", 'Jean-Baptiste LECANU'],
    ['S49', '11:35', '12:00', 'Margaux', 'TC', 'AT', 'Prévention et prise en charge des mucocèles après chirurgie endoscopique', 'Ahmed ALHARBI'],
    ['S88', '11:35', '12:00', 'Pessac', 'DV', 'AT', "Exploration fibroscopique sous hypnose de l'enfant et de l'adulte", 'Olivier DUFFAS; Charlotte CELLIER'],
    ['S44', '11:35', '12:00', 'Pomerol', 'TC', 'AT', "Choisir le meilleur lambeau pour l'aile narinaire et la pointe nasale", 'Philippe BOUDARD'],
    ['S51', '11:35', '12:00', 'StJulien', 'TU', 'AT', 'Tumeurs osseuses et fibro-osseuses naso-sinusiennes', 'Clair VANDERSTEEN'],
    ['S52', '12:05', '13:00', 'AmphiA', 'DV', 'LE', "L'obstruction nasale : avons-nous tout compris ?", 'Basile LANDIS'],
    ['S165', '12:05', '13:00', 'AmphiC', 'SR', 'AT', 'My work in rhinoplasty VS AI', 'Arturo RAMIREZ LEAL'],
    ['S63', '12:05', '13:00', 'StJulien', 'DV', 'LE', 'La rhinologie au Service de Santé des Armées', 'Ludovic DE GABORY; Jean-Baptiste MORVAN'],
    ['S54', '13:00', '14:30', 'Hall', 'SE', 'DI', 'Ateliers de dissection pour les internes', 'Florent CARSUZAA; Charles-Henri HASSAN'],
    ['S142', '13:00', '14:00', 'Hall', 'PS', 'DI', "Cocktail déjeunatoire et visite de l'exposition", ''],
    ['S55', '14:00', '14:55', 'AmphiA', 'AP', 'CC', "Cas cliniques : les rhinites difficiles sous l'égide de la SFA", 'Somar KASSAB; Habib CHABANE; Céline PALUSSIERE'],
    ['S126', '14:00', '14:25', 'AmphiC', 'DV', 'AT', 'Dacryocystorhinostomie endonasale : prise en charge des récidives', 'Fayçal CHETTIBI'],
    ['S162', '14:00', '14:25', 'Margaux', 'SO', 'AT', 'Comment sélectionner les patients pour la stimulation du XII ?', 'Duc Trung NGUYEN'],
    ['S60', '14:00', '14:55', 'Pessac', 'TU', 'RE', 'Recommandations du REFCOR — cancer des sinus par l’exemple', 'Antoine MOYA PLANA; Juliette THARIAT; Claire CASTAIN'],
    ['S78', '14:00', '14:25', 'Pomerol', 'RP', 'LE', 'Le cycle nasal : physiologie, pathologie, implications thérapeutiques', 'Geoffrey MORTUAIRE'],
    ['S1', '14:00', '14:25', 'StJulien', 'UR', 'AT', 'Gestion des sinusites infectieuses compliquées', 'Mélodie KERIMIAN'],
    ['S58', '14:00', '14:55', 'Sauternes', 'DV', 'LE', 'Épidémiologie et organisation de la rhinologie au Sénégal', 'Bay Karim DIALLO'],
    ['S106', '14:30', '14:55', 'AmphiC', 'OD', 'AT', "Rôle des cytokines dans les troubles de l'olfaction", 'Maxime FIEUX'],
    ['S163', '14:30', '14:55', 'Margaux', 'DV', 'AT', 'Kystes et fistules du dos du nez', 'François SIMON'],
    ['S164', '14:30', '14:55', 'Pomerol', 'SO', 'AT', "Anatomie comparative sous sommeil induit du primate à l'homme", 'Mickaël PAPAXANTHOS'],
    ['S56', '15:00', '15:30', 'AmphiA', 'TC', 'VC', "Les nouvelles voies d'abord maxillaires et frontales", 'Justin MICHEL; Dario EBODE'],
    ['S98', '15:00', '15:30', 'AmphiC', 'TC', 'VC', "L'ethmoïdectomie fonctionnelle pas à pas, trucs et astuces", 'Maxime FIEUX; Clémentine DAVEAU'],
    ['S62', '15:00', '15:30', 'Margaux', 'TC', 'AT', 'Réparation des pertes de substance de la columelle', 'Olivier MALARD'],
    ['S61', '15:00', '15:30', 'Pessac', 'RP', 'AT', "Qu'attendre des traitements sur l'odorat dans la polypose ?", 'Emilie BEQUIGNON; Clair VANDERSTEEN'],
    ['S57', '15:00', '15:30', 'Pomerol', 'AP', 'AT', 'Pourquoi et comment se mettre à la rhino-allergologie ?', 'David SCHMITT'],
    ['S64', '15:00', '15:30', 'StJulien', 'RP', 'AT', 'Les sinusites œdémato-purulentes : mise à jour', 'Jean-François PAPON'],
    ['S59', '15:00', '15:30', 'Sauternes', 'IM', 'AT', 'Imagerie des lésions naso-sinusiennes : quiz didactique', 'Benjamin VERILLAUD'],
    ['S65', '15:30', '16:00', 'Hall', 'PS', 'DI', "Pause et visite de l'exposition", ''],
    ['S66', '16:00', '17:05', 'AmphiA', 'SO', 'CC', "Cas cliniques : nez & sommeil sous l'égide de l'AFSORL", 'Valentin FAVIER; Xavier DUFOUR; Pierre-Louis BASTIER'],
    ['S117', '16:00', '16:30', 'AmphiC', 'TC', 'AT', 'Respiration nasale et croissance faciale : applications pratiques', 'Joelle HUTH'],
    ['S123', '16:00', '16:30', 'Margaux', 'RP', 'AT', "De la lésion à la régénération : l'épithélium après chirurgie de la polypose", 'Martin DESROSIERS'],
    ['S73', '16:00', '16:30', 'Pessac', 'SR', 'AT', 'La chirurgie de la valve', 'Clair VANDERSTEEN'],
    ['S68', '16:00', '16:30', 'Pomerol', 'IM', 'AT', 'Prise en charge des opacités sphénoïdales', 'Olivier MALARD'],
    ['S167', '16:00', '16:30', 'StJulien', 'AP', 'AT', "L'exploration moléculaire de l'allergie : quand, pourquoi ?", 'Céline PALUSSIERE'],
    ['S71', '16:00', '17:05', 'Sauternes', 'RP', 'SY', "Symposium AstraZeneca — De l'épithélium aux biothérapies", 'Candice LA CROIX; Elie SERRANO; Florent CARSUZAA'],
    ['S118', '16:35', '17:35', 'AmphiC', 'SE', 'DI', "Session Grand Public : les troubles de l'odorat et leurs solutions", 'Ludovic DE GABORY; Jean-Michel MAILLARD'],
    ['S76', '16:35', '17:05', 'Margaux', 'TU', 'AT', 'Que sait-on sur les nouveaux cancers naso-sinusiens ?', 'Antoine MOYA PLANA'],
    ['S74', '16:35', '17:00', 'Pessac', 'TC', 'AT', 'Traumatisme trans-facial et agent vulnérant en place : quelle stratégie ?', 'Jean-Baptiste MORVAN'],
    ['S18', '16:35', '17:05', 'Pomerol', 'IM', 'LE', 'Comment lire une IRM naso-sinusienne ?', 'Sandrine MOLINIER'],
    ['S79', '16:35', '17:05', 'StJulien', 'TC', 'AT', 'Comment se repérer et opérer le recessus frontal ?', 'Jean-François PAPON'],
    ['S67', '17:10', '17:35', 'AmphiA', 'TC', 'VC', 'Techniques de sphénoïdotomie : cas pratiques', 'Xavier DUFOUR'],
    ['S77', '17:10', '17:35', 'Margaux', 'SR', 'VC', 'Voie externe de rhinoplastie : comment débuter pas à pas ?', 'Benjamin VAIREL'],
    ['S166', '17:10', '17:35', 'Pessac', 'RP', 'AT', "La barrière épithéliale, l'inflammation de type II et les biothérapies", 'Mickaël PAPAXANTHOS'],
    ['S70', '17:10', '17:35', 'Pomerol', 'SR', 'LE', 'Déviations (rhino)septales : quelle technique pour quels objectifs ?', 'Guillaume DE BONNECAZE'],
    ['S80', '17:10', '17:35', 'StJulien', 'UR', 'VC', "Coagulation de l'artère sphéno-palatine", 'Cécile RUMEAU'],
    ['S72', '17:10', '17:35', 'Sauternes', 'UR', 'AT', 'Gestion des complications en chirurgie endoscopique', 'Clair VANDERSTEEN'],
    ['S168', '17:40', '18:30', 'AmphiC', 'DV', 'DI', "Conseil d'administration de l'AFR", ''],
  ];

  const SAM = [
    ['S81', '08:30', '08:55', 'AmphiA', 'TC', 'VC', 'Comment je fais la DCR ?', 'Amandine LECHOT'],
    ['S128', '08:30', '08:55', 'AmphiC', 'SO', 'AT', 'Comment faites-vous une polygraphie chez un enfant en ville ?', 'Pascal FLORES'],
    ['S103', '08:30', '08:55', 'Margaux', 'RP', 'AT', 'Biothérapie dans la PNS : que faire quand ça ne marche pas ?', 'Florent CARSUZAA'],
    ['S99', '08:30', '09:25', 'Pessac', 'RP', 'RE', "Recommandations de l'AFR par l'exemple sur la PNS", 'Guillaume DE BONNECAZE; Jean-François PAPON'],
    ['S87', '08:30', '08:55', 'Pomerol', 'SR', 'AT', 'Réparation du dorsum nasal : les solutions pratiques', 'Martin PENICAUD'],
    ['S109', '08:30', '08:55', 'StJulien', 'TC', 'AT', 'Abord et optimisation des chirurgies du sphénoïde', 'Valentin FAVIER'],
    ['S94', '08:30', '08:55', 'Sauternes', 'TU', 'LE', 'Tout savoir sur le papillome inversé et sa prise en charge', 'Ludovic DE GABORY'],
    ['S82', '09:00', '09:55', 'AmphiA', 'OD', 'TR', "Quelle prise en charge de l'odorat aujourd'hui ?", 'Basile LANDIS; Philippe ROMBAUX; Duc Trung NGUYEN'],
    ['S75', '09:00', '09:25', 'AmphiC', 'SR', 'AT', "L'essentiel de la rhinoplastie de préservation", 'Vincent PATRON'],
    ['S104', '09:00', '09:25', 'Margaux', 'IM', 'AT', 'Quand demander une IRM dans les rhinosinusites ?', 'Clémentine DAVEAU; Nicolas VOISIN'],
    ['S124', '09:00', '09:25', 'Pomerol', 'SR', 'AT', 'Septoplastie endoscopique : notre philosophie', 'Fayçal CHETTIBI'],
    ['S110', '09:00', '09:25', 'StJulien', 'DV', 'AT', "L'obstruction nasale déclive chez les patients apnéiques", 'Pierre-Louis BASTIER'],
    ['S95', '09:00', '09:55', 'Sauternes', 'AP', 'SY', 'Symposium Zambon — Prise en charge de la rhinite allergique', 'Elie SERRANO; Philippe DEVILLIER; Pham-Thi NHÂN'],
    ['S125', '09:30', '10:00', 'AmphiC', 'DV', 'AT', 'La prise en charge des atrésies choanales unilatérales', 'Semia SAHTOUT'],
    ['S105', '09:30', '09:55', 'Margaux', 'RP', 'AT', 'Dyskinésie ciliaire primitive : registre européen EPIC-PCD', 'Jean-François PAPON'],
    ['S100', '09:30', '10:30', 'Pessac', 'DV', 'CC', "Cas clinique dents & sinus sous l'égide de la SFCO", 'Ludovic DE GABORY; Sylvain CATROS; Patrick LIMBOUR'],
    ['S89', '09:30', '09:55', 'Pomerol', 'TC', 'AT', "Appréhender l'orbite en chirurgie endoscopique", 'Mathieu VEYRAT'],
    ['S111', '09:30', '09:55', 'StJulien', 'TC', 'AT', "Carcinomes péri-orificiels du nez : de l'exérèse à la reconstruction", 'Guillaume DE BONNECAZE'],
    ['S83', '10:00', '10:30', 'AmphiA', 'SR', 'VC', 'La rhinoplastie médicale : un outil indispensable', 'Thomas RADULESCO'],
    ['S127', '10:00', '10:30', 'AmphiC', 'AP', 'AT', 'La rhinite allergique en pratique : qui peut faire quoi ?', 'Gaelle RAPIDIE'],
    ['S120', '10:00', '10:30', 'Margaux', 'SR', 'AT', 'Les ensellures nasales : prévention et traitement', 'Philippe ROMBAUX'],
    ['S90', '10:00', '10:30', 'Pomerol', 'TU', 'AT', 'Fibrome nasopharyngé : stratégie 2026 de prise en charge', 'Benjamin VERILLAUD'],
    ['S112', '10:00', '10:30', 'StJulien', 'DV', 'LE', 'Lésions nasales induites par la cocaïne', 'Vincent BEDARIDA'],
    ['S96', '10:00', '10:30', 'Sauternes', 'TC', 'VC', 'Le lambeau naso-septal pas à pas', 'Jean-François PAPON'],
    ['S155', '10:30', '11:00', 'Hall', 'PS', 'DI', "Pause et visite de l'exposition", ''],
    ['S91', '10:30', '12:00', 'Hall', 'SE', 'DI', 'Ateliers de dissection pour les internes', 'Florian CHATELET; Nicolas VOISIN'],
    ['S85', '11:00', '12:00', 'AmphiA', 'DV', 'RE', "Recommandations de l'AFR sur les soins péri-opératoires en rhinologie", 'Ludovic DE GABORY; Valentin FAVIER; Clair VANDERSTEEN'],
    ['S121', '11:00', '11:30', 'AmphiC', 'RP', 'AT', 'La chirurgie des reprises dans la polypose naso-sinusienne', 'Fayçal CHETTIBI'],
    ['S107', '11:00', '11:25', 'Margaux', 'TU', 'AT', "Gestion de l'envahissement orbitaire des tumeurs naso-sinusiennes", 'Antoine MOYA PLANA'],
    ['S101', '11:00', '11:25', 'Pessac', 'DV', 'LE', 'Le PRP en rhinologie : gadget ou avancée ?', 'Dario EBODE'],
    ['S92', '11:00', '11:25', 'Pomerol', 'SR', 'AT', 'Alternative à la dépose / repose', 'Amandine LECHOT'],
    ['S113', '11:00', '12:00', 'StJulien', 'DV', 'IN', 'Actualité sur la recherche clinique en rhinologie', 'Thomas RADULESCO; Mathieu VEYRAT; Vanessa ADEWOLE'],
    ['S97', '11:00', '11:25', 'Sauternes', 'TC', 'VC', 'Septectomie frontale endoscopique par voie transseptale', 'Cécile RUMEAU'],
    ['S161', '11:30', '12:00', 'AmphiC', 'SO', 'VC', 'Réaliser et interpréter une endoscopie sous sommeil induit', 'Mélodie KERIMIAN'],
    ['S108', '11:30', '12:00', 'Margaux', 'SR', 'AT', 'La rhinoplastie endoscopique', 'Justin MICHEL'],
    ['S102', '11:30', '12:00', 'Pessac', 'UR', 'AT', 'Complications per-opératoires en chirurgie endonasale : je fais quoi ?', 'Chloé MONNOT'],
    ['S93', '11:30', '12:00', 'Pomerol', 'DV', 'AT', 'Sécrétions, croûtes et crénothérapie', 'Emmanuelle MOUCHON'],
    ['S119', '11:30', '12:00', 'Sauternes', 'TC', 'VC', 'La dacryocystorhinostomie aux instruments froids', 'Azeddine LACHKAR'],
    ['S86', '12:00', '13:00', 'AmphiA', 'SE', 'DI', 'Les essentiels du congrès — Remise du prix de l’AFR', ''],
  ];

  function toMin(t) { const [h, m] = t.split(':').map(Number); return h * 60 + m; }

  function build(rows, dayId) {
    return rows.map((r) => ({
      id: r[0], dayId, start: r[1], end: r[2], startMin: toMin(r[1]), endMin: toMin(r[2]),
      room: r[3], theme: r[4], format: r[5], title: r[6],
      speakers: r[7] ? r[7].split(';').map((s) => s.trim()) : [],
    }));
  }

  const DAYS = [
    { id: 'jeu', short: 'Jeu', dom: '18', label: 'Jeudi 18 juin', sessions: build(JEU, 'jeu') },
    { id: 'ven', short: 'Ven', dom: '19', label: 'Vendredi 19 juin', sessions: build(VEN, 'ven') },
    { id: 'sam', short: 'Sam', dom: '20', label: 'Samedi 20 juin', sessions: build(SAM, 'sam') },
  ];

  window.RHINO = { THEMES, FORMATS, ROOMS, ROOM_ORDER, DAYS };
})();
